# Book settings
title: Clases online con Jupyter
author: Publiconsulting Media
logo: docs/images/logo.png

latex:
  latex_documents:
    targetname: book.tex

exclude_patterns: [file-types/include-rst.rst]

execute:
  execute_notebooks: cache

parse:
  myst_extended_syntax: true

html:
  google_analytics_id: UA-52617120-7
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://publiconsulting.com/
  comments:
    hypothesis: true

repository:
  url: https://github.com/Jero2760/Clases_online_con_Jupyter
  branch: master
  path_to_book: "docs"

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

latex:
  latex_engine: xelatex
